HTTP/1.1 200 OK
x-clerk-auth-reason: dev-browser-missing
x-clerk-auth-status: signed-out
x-middleware-rewrite: /api/billing/plans
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
content-type: application/json
Date: Mon, 23 Feb 2026 15:00:23 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

{"plans":[{"id":"5a09080b-65cb-4058-8d5b-6bb0ea2f4079","planCode":"free","displayName":"Free","billingInterval":"month","priceMinor":0,"currency":"USD","monthlyCredits":100,"active":true,"createdAt":"2026-02-23T15:00:23.463Z"},{"id":"5da95228-320a-47b2-a6bd-3c14d1eccc99","planCode":"starter","displayName":"Starter","billingInterval":"month","priceMinor":1900,"currency":"USD","monthlyCredits":2500,"active":true,"createdAt":"2026-02-23T15:00:23.463Z"},{"id":"b4f1f1a0-8b78-4cd2-a7e7-75a85ae6bd26","planCode":"pro","displayName":"Pro","billingInterval":"month","priceMinor":4900,"currency":"USD","monthlyCredits":8000,"active":true,"createdAt":"2026-02-23T15:00:23.463Z"},{"id":"171d70b0-c2dd-4666-aa91-ddcc0ae58df3","planCode":"team","displayName":"Team","billingInterval":"month","priceMinor":19900,"currency":"USD","monthlyCredits":40000,"active":true,"createdAt":"2026-02-23T15:00:23.463Z"}]}