HTTP/1.1 500 Internal Server Error
x-clerk-auth-reason: dev-browser-missing
x-clerk-auth-status: signed-out
x-middleware-rewrite: /api/internal/pricing/versions
vary: rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch
Date: Mon, 23 Feb 2026 15:04:23 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

